make sure that vcap does not start if the network is not available yet.

diff --git a/dev_setup/cookbooks/deployment/templates/default/vcap.erb b/dev_setup/cookbooks/deployment/templates/default/vcap.erb
--- a/dev_setup/cookbooks/deployment/templates/default/vcap.erb
+++ b/dev_setup/cookbooks/deployment/templates/default/vcap.erb
@@ -4,13 +4,24 @@
 [ -z "$USER" ] && export USER=<%= node[:deployment][:user] %>
 [ -z "$TERM" ] && export TERM=xterm
 
-# make sure avahi is publishing the aliases if avahi-publishaliases is installed
-[ -f /usr/bin/avahi-publish-aliases -a ! -f /tmp/avahi-publish-alias.pid ] && /usr/bin/avahi-publish-aliases
-
 _vcap_log=<%= node[:deployment][:log_path] %>/vcap.log
 #don't log status calls:
 [ "$1" == "status" ] && _vcap_log=/dev/null
 echo `date +%Y-%m-%d-%H%M%S`" vcap called with $@" | tee -a $_vcap_log
+
+# check that the network is correctly setup on this VM: at least one IP that is not the local loop:
+ip=`/sbin/ifconfig | grep "inet addr" | grep -v "127.0.0.1" | awk '{ print $2 }' | awk -F: '{ print $2 }'`
+if [ -z "$ip" ]; then
+  if [ -d "/etc/issue.d/volatile.d" ]; then
+    touch /etc/issue.d/volatile.d/K50_applications_status
+    echo "Cloudfoundry cannot start: No network is available." > /etc/issue.d/volatile.d/K50_applications_status
+  fi
+  echo "Cloudfoundry cannot start: No network is available." >> $_vcap_log
+  exit 1
+fi
+
+# make sure avahi is publishing the aliases if avahi-publishaliases is installed
+[ -f /usr/bin/avahi-publish-aliases -a ! -f /tmp/avahi-publish-alias.pid ] && /usr/bin/avahi-publish-aliases
 
 # Make sure the binaries for this vcap runtime are ready:
 if [ -z "$CLOUD_FOUNDRY_CONFIG_PATH" ]; then
@@ -44,13 +55,12 @@ if [ "$do_reconfig" == "true" ]; then
      ruby start_register_app.rb >> $_vcap_log 2>&1 # | tee -a $_vcap_log # can't redirect
   fi
 
-
   cd /home/<%= node[:deployment][:user] %>
   echo "calling vmc_knife to make sure the urls are up to date." | tee -a $_vcap_log
   vmc_knife login | tee -a $_vcap_log
   vmc_knife configure-applications | tee -a $_vcap_log
   vmc_knife configure-vcap-etc-hosts | tee -a $_vcap_log
-  vmc_knife configure-vcap-mdns | tee -a $_vcap_log
+  #vmc_knife configure-vcap-mdns | tee -a $_vcap_log
 fi
 
 #call vcap with the cmd-line args:
